export enum UserErrorCode {
  E404_USER = 'E404_USER',
  E400_USER_INACTIVE = 'E400_USER_INACTIVE',
  E400_USER_ALREADY_EXISTS = 'E400_USER_ALREADY_EXISTS',
  E400_USER_EMAIL_ALREADY_EXISTS = 'E400_USER_EMAIL_ALREADY_EXISTS',
  E400_USER_USERNAME_OR_EMAIL_REQUIRED = 'E400_USER_USERNAME_OR_EMAIL_REQUIRED',
}
